### PR TITLE
Build cleanups

### PR DESCRIPTION
**Pull request by hadess**
Cleanups to remove a lot of generated files, and errors on a modern Linux system (the sources don't compile though).

### CODE REVIEW

**Comment by pbosquetg1** [comment]
Some of the code i added is windows only. would be nice to have a linux/macos version

**Comment by hadess** [comment]
> Some of the code i added is windows only. would be nice to have a linux/macos version

I think those patches are ready to be merged, if they work for you in Windows. Let me know which files are Windows-specific and I can take a look.

**Comment by pascalorama** [comment]
changes merged , sorry for the delay , just started a new job ;)

**Comment by hadess** [comment]
No problems :)

**Pull request merged**
